#!/bin/bash -i
export design="Ariane"
export GLOBAL_SEED=111
export ROOT_DIR="./logs/${design}_run1"
export REVERB_PORT=8008
export NUM_ITERATION=2
export NUM_EPISODE_PER_ITERATION=16
export BATCH_SIZE=64
export NETLIST_FILE="./circuit_training/environment/test_data/ariane/netlist.pb.txt"
export INIT_PLACEMENT="./circuit_training/environment/test_data/ariane/initial.plc"
